name: Snake and Bloom Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: shahi0121
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Push Snake SVG to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "update contribution snake"
          add: "output/github-contribution-grid-snake.svg"

  generate-bloom:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Bloom Graph Generator
        run: |
          git clone https://github.com/ashutosh1919/commit-bloom.git
          cd commit-bloom
          npm install
          npm run generate -- --username shahi0121 --output ../BloomGraph/bloom-contribution.svg

      - name: Push Bloom Graph SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "update bloom graph"
          add: "BloomGraph/bloom-contribution.svg"
